---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: full
    run_list:
      - recipe[opentsdb::install]
      - recipe[opentsdb::start]
      - recipe[opentsdb::install_elasticsearch]
      - recipe[opentsdb::install_grafana]
    attributes:
